server:
  port: 8000
dubbo:
  scan:
    base-packages: com.springcloud.dubbo_provider.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://192.168.44.129
spring:
  application:
    name: dubbo-spring-cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.129:8848
  main:
    allow-bean-definition-overriding: true