server:
  port: 8080
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meteor1993/SpringCloudLearning
          search-paths: chapter6/springcloud-config
          username: inwsy@hotmail.com
          password: wsy136736247.
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 101.132.124.125
    port: 5672
    username: admin
    password: wsy@123456
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/