server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  retryable: true
  ribbon:
    eager-load:
      enabled: true
  routes:
    consumer-server:
      path: /consumer/**
      serviceId: consumer-server
ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true